# Generated by Django 5.0 on 2024-11-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('user_creation', models.CharField(default='admin', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario_modificacion', models.CharField(default='admin', max_length=50)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
