# Generated by Django 5.0 on 2024-08-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
