# Generated by Django 5.0 on 2024-11-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0003_type_creation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=10)),
                ('id_user', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('creation_user', models.CharField(default='admin', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_user', models.CharField(default='admin', max_length=50)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='type',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
