# Generated by Django 5.0 on 2024-09-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0003_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='perfil_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
