# Generated by Django 5.0 on 2024-11-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0004_responsible_alter_type_modification_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('status', models.IntegerField(default=1)),
                ('creation_user', models.CharField(default='admin', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_user', models.CharField(default='admin', max_length=50)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='responsible',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
