# Generated by Django 5.0 on 2024-11-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0005_customer_alter_responsible_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('creation_user', models.CharField(default='admin', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_user', models.CharField(default='admin', max_length=50)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('status', models.IntegerField(default=1)),
                ('creation_user', models.CharField(default='admin', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_user', models.CharField(default='admin', max_length=50)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.customer')),
                ('responsible_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.responsible')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.type')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.state')),
            ],
        ),
    ]
