# Generated by Django 5.0 on 2024-11-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0006_state_proyect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyect',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='proyect',
            old_name='responsible_id',
            new_name='responsible',
        ),
        migrations.RenameField(
            model_name='proyect',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='proyect',
            old_name='type_id',
            new_name='type',
        ),
    ]
