# Generated by Django 5.0 on 2024-11-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0007_rename_customer_id_proyect_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('creation_user', models.CharField(default='admin', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_user', models.CharField(default='admin', max_length=50)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
