# Generated by Django 5.0 on 2024-11-20 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0008_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Statu',
        ),
    ]
