# Generated by Django 5.0 on 2024-11-20 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0009_rename_status_statu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('creation_user', models.CharField(default='admin', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_user', models.CharField(default='admin', max_length=50)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyect.statu')),
            ],
        ),
    ]
