# Generated by Django 5.0 on 2024-11-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0015_alter_decorator_proyects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
