# Generated by Django 5.0 on 2024-11-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0016_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
