# Generated by Django 5.0 on 2024-12-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0017_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
