# Generated by Django 5.0 on 2024-12-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0018_customer_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('proyect_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
