# Generated by Django 5.0 on 2024-12-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0019_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_event_id', models.IntegerField(choices=[('1', 'Create event'), ('2', 'Comment')], default=0)),
                ('proyect_id', models.IntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('user_id', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
