# Generated by Django 5.0 on 2024-12-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0023_place_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_event_id',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Create event'), (2, 'Comment')], default=0),
        ),
    ]
