# Generated by Django 5.0 on 2024-12-14 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0024_alter_event_type_event_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='catalogs/')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('creation_user', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_creation_set', to=settings.AUTH_USER_MODEL)),
                ('modification_user', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_modification_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
