# Generated by Django 5.0 on 2024-12-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0025_catalog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
