# Generated by Django 5.0 on 2024-12-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0031_alter_item_notes_item_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
