# Generated by Django 5.0 on 2024-12-26 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0032_alter_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.item')),
            ],
        ),
    ]
