# Generated by Django 5.0 on 2024-12-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0033_item_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_images',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
