# Generated by Django 5.0 on 2024-12-26 23:26

import proyect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0034_item_images_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_images',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='item_images',
            name='imagen',
        ),
        migrations.AddField(
            model_name='item_images',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='item_images',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=proyect.models.get_file_path_img),
        ),
    ]
