# Generated by Django 5.0 on 2024-12-27 00:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0035_rename_title_item_images_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_images',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
