# Generated by Django 5.0 on 2025-01-04 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0036_alter_item_images_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='date_proposed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='responsible',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyect.responsible'),
        ),
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
