# Generated by Django 5.0 on 2025-01-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0037_item_date_end_item_date_proposed_item_responsible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_images',
            name='type',
            field=models.IntegerField(choices=[(1, 'Image'), (2, 'Material'), (3, 'Comment')], default=1),
        ),
    ]
