# Generated by Django 5.0 on 2025-01-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0038_item_images_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
