# Generated by Django 5.0 on 2025-01-08 02:25

import proyect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0039_attribute_order_category_order_subcategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=proyect.models.get_file_path_img_att),
        ),
    ]
