# Generated by Django 5.0 on 2025-01-08 02:30

import proyect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0040_attribute_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='file',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='order',
        ),
        migrations.AddField(
            model_name='category_attribute',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='attributes'),
            # field=models.ImageField(blank=True, null=True, upload_to=proyect.models.get_file_path_img_att),
        ),
        migrations.AddField(
            model_name='category_attribute',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
