# Generated by Django 5.0 on 2025-01-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0041_remove_attribute_file_remove_attribute_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
