# Generated by Django 5.0 on 2025-01-12 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0042_proyect_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('creation_user', models.CharField(default='admin', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_user', models.CharField(default='admin', max_length=50)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.subcategory')),
            ],
        ),
    ]
