# Generated by Django 5.0 on 2025-01-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0043_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='proyect_id',
        ),
        migrations.AddField(
            model_name='event',
            name='proyect',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='proyect.proyect'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_event_id',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Create event'), (2, 'Comment'), (3, 'Create item'), (4, 'Delete item'), (5, 'Upload file/comment'), (6, 'Change state')], default=0),
        ),
    ]
