# Generated by Django 5.0 on 2025-01-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0048_alter_type_creation_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='creation_user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='modification_user',
            new_name='modification_by',
        ),
    ]
