# Generated by Django 5.0 on 2025-01-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0049_rename_creation_user_type_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='created_by',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='modification_by',
            new_name='modification_by_user',
        ),
    ]
