# Generated by Django 5.0 on 2025-01-26 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0064_remove_item_creation_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Comment_State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.item')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.state')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Other'), (1, 'Create event'), (2, 'Comment'), (3, 'Create item'), (4, 'Delete item'), (5, 'Upload file/comment'), (6, 'Change state')], default=2)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.item')),
            ],
        ),
    ]
