# Generated by Django 5.0 on 2025-02-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0069_alter_attribute_created_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
