# Generated by Django 5.0 on 2025-02-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0070_state_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='buttonName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
