# Generated by Django 5.0 on 2025-03-01 00:50

import django.db.models.deletion
import django.utils.timezone
import proyect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0071_state_buttonname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by_user', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modification_by_user', models.IntegerField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.proyect')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.state')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_State_Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, upload_to=proyect.models.get_file_path_comment)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('comment_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.comment_state')),
            ],
        ),
    ]
