# Generated by Django 5.0 on 2025-03-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0072_comment_state_comment_state_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_images',
            name='qty',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
