# Generated by Django 5.0 on 2025-03-19 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0074_item_files_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='proyect',
            name='state',
        ),
        migrations.AlterField(
            model_name='comment_state_files',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='generalComments'),
        ),
        migrations.AlterField(
            model_name='item_comment_state_files',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='generalComments'),
        ),
        migrations.AlterField(
            model_name='item_files',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='item_images',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_by_user', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.proyect')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.state')),
            ],
        ),
    ]
