# Generated by Django 5.0 on 2025-03-19 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0075_remove_group_category_remove_item_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='proyect',
        ),
        migrations.AddField(
            model_name='item',
            name='workorder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyect.workorder'),
            preserve_default=False,
        ),
    ]
