# Generated by Django 5.0 on 2025-03-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0077_remove_event_proyect_event_workorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_files',
            name='type',
        ),
        migrations.RemoveField(
            model_name='item_images',
            name='type',
        ),
    ]
