# Generated by Django 5.0 on 2025-03-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0079_item_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_files',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='item_images',
            name='qty',
        ),
    ]
