# Generated by Django 5.0 on 2025-03-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0080_remove_item_files_qty_remove_item_images_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_state_files',
            name='comment_state',
        ),
        migrations.DeleteModel(
            name='Comment_State',
        ),
        migrations.DeleteModel(
            name='Comment_State_Files',
        ),
    ]
