# Generated by Django 5.0 on 2025-03-22 20:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0081_remove_comment_state_files_comment_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder_Comment_State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by_user', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modification_by_user', models.IntegerField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.state')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder_Comment_State_Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, upload_to='generalComments')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('workorder_comment_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.workorder_comment_state')),
            ],
        ),
    ]
