# Generated by Django 5.0 on 2025-03-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0082_workorder_comment_state_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_Comments',
            new_name='Item_Comment',
        ),
        migrations.RenameModel(
            old_name='Item_Comment_State_Files',
            new_name='Item_Comment_State_File',
        ),
        migrations.RenameModel(
            old_name='Item_Files',
            new_name='Item_File',
        ),
        migrations.RenameModel(
            old_name='Item_Images',
            new_name='Item_Image',
        ),
        migrations.RenameModel(
            old_name='Item_Materials',
            new_name='Item_Material',
        ),
        migrations.RenameModel(
            old_name='WorkOrder_Comment_State_Files',
            new_name='WorkOrder_Comment_State_File',
        ),
    ]
