# Generated by Django 5.0 on 2025-03-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0083_rename_item_comments_item_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Decorator',
            new_name='ProyectDecorator',
        ),
    ]
