# Generated by Django 5.0 on 2025-03-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0084_rename_decorator_proyectdecorator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_Attribute',
            new_name='CategoryAttribute',
        ),
        migrations.RenameModel(
            old_name='Item_Attribute',
            new_name='ItemAttribute',
        ),
        migrations.RenameModel(
            old_name='Item_Comment',
            new_name='ItemComment',
        ),
        migrations.RenameModel(
            old_name='Item_Comment_State',
            new_name='ItemCommentState',
        ),
        migrations.RenameModel(
            old_name='Item_Comment_State_File',
            new_name='ItemCommentStateFile',
        ),
        migrations.RenameModel(
            old_name='Item_File',
            new_name='ItemFile',
        ),
        migrations.RenameModel(
            old_name='Item_Image',
            new_name='ItemImage',
        ),
        migrations.RenameModel(
            old_name='Item_Material',
            new_name='ItemMaterial',
        ),
        migrations.RenameModel(
            old_name='WorkOrder_Comment_State',
            new_name='WorkOrderCommentState',
        ),
        migrations.RenameModel(
            old_name='WorkOrder_Comment_State_File',
            new_name='WorkOrderCommentStateFile',
        ),
    ]
