# Generated by Django 5.0 on 2025-03-24 00:43

import proyect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0085_rename_category_attribute_categoryattribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemcommentstatefile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=proyect.models.getUploadTo),
        ),
        migrations.AlterField(
            model_name='itemfile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=proyect.models.getUploadTo),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=proyect.models.getUploadTo),
        ),
        migrations.AlterField(
            model_name='itemmaterial',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=proyect.models.getUploadTo),
        ),
        migrations.AlterField(
            model_name='workordercommentstatefile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=proyect.models.getUploadTo),
        ),
    ]
