# Generated by Django 5.0 on 2025-03-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0086_responsible_color_alter_itemcommentstatefile_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label_text', models.CharField(max_length=255)),
                ('language_code', models.CharField(default='en', max_length=10)),
            ],
        ),
    ]
