# Generated by Django 5.0 on 2025-03-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0087_uielements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UIElements',
            new_name='UIElement',
        ),
    ]
