# Generated by Django 5.0 on 2025-03-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0088_rename_uielements_uielement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='workorder',
            name='modification_by_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='uielement',
            name='label_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
