# Generated by Django 5.0 on 2025-04-06 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0089_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryattribute',
            name='file',
        ),
        migrations.AddField(
            model_name='attribute',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyect.responsible'),
        ),
        migrations.AlterField(
            model_name='proyectdecorator',
            name='proyects',
            field=models.ManyToManyField(blank=True, related_name='decoratorProyects', to='proyect.proyect'),
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='attributes')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_by_user', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_by_user', models.IntegerField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.attribute')),
            ],
        ),
    ]
