# Generated by Django 5.0 on 2025-04-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0091_remove_itemattribute_created_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaterial',
            name='date_received',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemmaterial',
            name='qty_received',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
