# Generated by Django 5.0 on 2025-04-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0092_itemmaterial_date_received_itemmaterial_qty_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quote',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
