# Generated by Django 5.0 on 2025-04-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0093_item_quote_alter_item_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='buttondescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
