# Generated by Django 5.0 on 2025-04-28 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0094_state_buttondescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='buttondescription',
            new_name='buttonDescription',
        ),
    ]
