# Generated by Django 5.0 on 2025-05-20 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0096_item_subcategory_alter_item_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyect.responsible'),
        ),
    ]
