# Generated by Django 5.0 on 2025-05-21 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0097_workorder_date_workorder_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='item',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='responsible',
        ),
        migrations.CreateModel(
            name='CalendarItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_by_user', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_by_user', models.IntegerField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.item')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyect.responsible')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarWorkOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_by_user', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_by_user', models.IntegerField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyect.responsible')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
