# Generated by Django 5.0 on 2025-05-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0098_remove_item_date_end_remove_item_responsible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
