# Generated by Django 5.0 on 2025-05-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0100_calendaritemcomment_calendaritemcommentfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendaritemcommentfile',
            name='calendar_item_comment',
        ),
        migrations.RemoveField(
            model_name='calendarworkordercomment',
            name='workorder',
        ),
        migrations.RemoveField(
            model_name='calendarworkordercommentfile',
            name='calendar_workorder_comment',
        ),
        migrations.DeleteModel(
            name='CalendarItemComment',
        ),
        migrations.DeleteModel(
            name='CalendarItemCommentFile',
        ),
        migrations.DeleteModel(
            name='CalendarWorkOrderComment',
        ),
        migrations.DeleteModel(
            name='CalendarWorkOrderCommentFile',
        ),
    ]
