# Generated by Django 5.0 on 2025-05-22 23:11

import django.db.models.deletion
import django.utils.timezone
import proyect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0101_remove_calendaritemcommentfile_calendar_item_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarItemComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by_user', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modification_by_user', models.IntegerField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('calendar_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.calendaritem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarItemCommentFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, upload_to=proyect.models.getUploadTo)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('calendar_item_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.calendaritemcomment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarWorkOrderComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by_user', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modification_by_user', models.IntegerField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('calendar_workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.calendarworkorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarWorkOrderCommentFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, upload_to=proyect.models.getUploadTo)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('calendar_workorder_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.calendarworkordercomment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
