# Generated by Django 5.0 on 2025-06-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0102_calendaritemcomment_calendaritemcommentfile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendaritem',
            old_name='date',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='calendarworkorder',
            old_name='date',
            new_name='date_start',
        ),
        migrations.AddField(
            model_name='calendaritem',
            name='date_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='calendarworkorder',
            name='date_end',
            field=models.DateTimeField(null=True),
        ),
    ]
