# Generated by Django 5.0 on 2025-06-08 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0103_rename_date_calendaritem_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaritem',
            name='allday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarworkorder',
            name='allday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='date_due',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyect.responsible'),
        ),
        migrations.AddField(
            model_name='itemcommentstate',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CalendarAppointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('allday', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_by_user', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_by_user', models.IntegerField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyect.responsible')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
