# Generated by Django 5.0 on 2025-06-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0104_calendaritem_allday_calendarworkorder_allday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarappointment',
            name='allday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='allday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='calendarworkorder',
            name='allday',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
