# Generated by Django 5.0 on 2025-06-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0105_alter_calendarappointment_allday_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalendarAppointment',
            new_name='CalendarTask',
        ),
    ]
