# Generated by Django 5.0 on 2025-06-15 22:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0106_rename_calendarappointment_calendartask'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarTaskComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by_user', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modification_by_user', models.IntegerField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('calendar_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.calendartask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
