# Generated by Django 5.0 on 2025-06-19 21:05

import django.db.models.deletion
import django.utils.timezone
import proyect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0107_calendartaskcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarTaskCommentFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, upload_to=proyect.models.getUploadTo)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('calendar_task_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.calendartaskcomment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
