# Generated by Django 5.0 on 2025-07-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0109_alter_workorder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='linkDescription',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='modalSubTitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='modalTitle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='negativeMessage',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='positiveMessage',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
