# Generated by Django 5.0 on 2025-07-20 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0110_state_linkdescription_state_modalsubtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyect.place'),
        ),
    ]
