# Generated by Django 5.0 on 2025-07-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0111_alter_item_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyect.state'),
        ),
    ]
