# Generated by Django 5.0 on 2025-07-20 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0112_event_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyect.item'),
        ),
    ]
