# Generated by Django 5.0 on 2025-07-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0113_event_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_event_id',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Create'), (2, 'Update'), (3, 'Delete')], default=0),
        ),
        migrations.AlterField(
            model_name='itemcomment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Create'), (2, 'Update'), (3, 'Delete')], default=2),
        ),
    ]
