# Generated by Django 5.0 on 2025-07-26 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0114_alter_event_type_event_id_alter_itemcomment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='proyect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyect.proyect'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyect.item'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyect.state'),
        ),
        migrations.AlterField(
            model_name='event',
            name='workorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyect.workorder'),
        ),
    ]
