# Generated by Django 5.0 on 2025-07-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0115_event_proyect_alter_event_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
