# Generated by Django 5.0 on 2025-10-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0116_alter_event_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='checkBoxDescription',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
