# Generated by Django 5.0 on 2025-10-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect', '0117_state_checkboxdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordercommentstate',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
